/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './root'
import { Route as DotModulesShellPagesUnauthenticatedLayoutRouteImport } from './modules/shell/pages/unauthenticated-layout'
import { Route as DotModulesWorkspacePagesOnboardingLayoutRouteImport } from './modules/workspace/pages/onboarding-layout'
import { Route as DotModulesShellPagesAuthenticatedLayoutRouteImport } from './modules/shell/pages/authenticated-layout'
import { Route as DotModulesAuthPagesRegisterPageRouteImport } from './modules/auth/pages/register-page'
import { Route as DotModulesAuthPagesLoginPageRouteImport } from './modules/auth/pages/login-page'
import { Route as DotModulesTopicPagesTopicPageRouteImport } from './modules/topic/pages/topic-page'
import { Route as DotModulesHomePagesSettingsPageRouteImport } from './modules/home/pages/settings-page'
import { Route as DotModulesHomePagesReviewPageRouteImport } from './modules/home/pages/review-page'
import { Route as DotModulesHomePagesProgressPageRouteImport } from './modules/home/pages/progress-page'
import { Route as DotModulesHomePagesLearnPageRouteImport } from './modules/home/pages/learn-page'
import { Route as DotModulesHomePagesAddWordPageRouteImport } from './modules/home/pages/add-word-page'
import { Route as DotModulesHomePagesAchievementsPageRouteImport } from './modules/home/pages/achievements-page'
import { Route as DotModulesHomePagesHomePageRouteImport } from './modules/home/pages/home-page'
import { Route as DotModulesWorkspacePagesCreateWorkspacePageRouteImport } from './modules/workspace/pages/create-workspace-page'
import { Route as DotModulesWordsPagesWordListPageRouteImport } from './modules/words/pages/word-list-page'

const DotModulesShellPagesUnauthenticatedLayoutRoute =
  DotModulesShellPagesUnauthenticatedLayoutRouteImport.update({
    id: '/_(unauthenticated)',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotModulesWorkspacePagesOnboardingLayoutRoute =
  DotModulesWorkspacePagesOnboardingLayoutRouteImport.update({
    id: '/_(onboarding)',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotModulesShellPagesAuthenticatedLayoutRoute =
  DotModulesShellPagesAuthenticatedLayoutRouteImport.update({
    id: '/_(authenticated)',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotModulesAuthPagesRegisterPageRoute =
  DotModulesAuthPagesRegisterPageRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => DotModulesShellPagesUnauthenticatedLayoutRoute,
  } as any)
const DotModulesAuthPagesLoginPageRoute =
  DotModulesAuthPagesLoginPageRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => DotModulesShellPagesUnauthenticatedLayoutRoute,
  } as any)
const DotModulesTopicPagesTopicPageRoute =
  DotModulesTopicPagesTopicPageRouteImport.update({
    id: '/topic',
    path: '/topic',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesHomePagesSettingsPageRoute =
  DotModulesHomePagesSettingsPageRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesHomePagesReviewPageRoute =
  DotModulesHomePagesReviewPageRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesHomePagesProgressPageRoute =
  DotModulesHomePagesProgressPageRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesHomePagesLearnPageRoute =
  DotModulesHomePagesLearnPageRouteImport.update({
    id: '/learn',
    path: '/learn',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesHomePagesAddWordPageRoute =
  DotModulesHomePagesAddWordPageRouteImport.update({
    id: '/add-word',
    path: '/add-word',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesHomePagesAchievementsPageRoute =
  DotModulesHomePagesAchievementsPageRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesHomePagesHomePageRoute =
  DotModulesHomePagesHomePageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesWorkspacePagesCreateWorkspacePageRoute =
  DotModulesWorkspacePagesCreateWorkspacePageRouteImport.update({
    id: '/onboarding/workspace',
    path: '/onboarding/workspace',
    getParentRoute: () => DotModulesWorkspacePagesOnboardingLayoutRoute,
  } as any)
const DotModulesWordsPagesWordListPageRoute =
  DotModulesWordsPagesWordListPageRouteImport.update({
    id: '/$topicId',
    path: '/$topicId',
    getParentRoute: () => DotModulesTopicPagesTopicPageRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DotModulesHomePagesHomePageRoute
  '/achievements': typeof DotModulesHomePagesAchievementsPageRoute
  '/add-word': typeof DotModulesHomePagesAddWordPageRoute
  '/learn': typeof DotModulesHomePagesLearnPageRoute
  '/progress': typeof DotModulesHomePagesProgressPageRoute
  '/review': typeof DotModulesHomePagesReviewPageRoute
  '/settings': typeof DotModulesHomePagesSettingsPageRoute
  '/topic': typeof DotModulesTopicPagesTopicPageRouteWithChildren
  '/login': typeof DotModulesAuthPagesLoginPageRoute
  '/register': typeof DotModulesAuthPagesRegisterPageRoute
  '/topic/$topicId': typeof DotModulesWordsPagesWordListPageRoute
  '/onboarding/workspace': typeof DotModulesWorkspacePagesCreateWorkspacePageRoute
}
export interface FileRoutesByTo {
  '/': typeof DotModulesHomePagesHomePageRoute
  '/achievements': typeof DotModulesHomePagesAchievementsPageRoute
  '/add-word': typeof DotModulesHomePagesAddWordPageRoute
  '/learn': typeof DotModulesHomePagesLearnPageRoute
  '/progress': typeof DotModulesHomePagesProgressPageRoute
  '/review': typeof DotModulesHomePagesReviewPageRoute
  '/settings': typeof DotModulesHomePagesSettingsPageRoute
  '/topic': typeof DotModulesTopicPagesTopicPageRouteWithChildren
  '/login': typeof DotModulesAuthPagesLoginPageRoute
  '/register': typeof DotModulesAuthPagesRegisterPageRoute
  '/topic/$topicId': typeof DotModulesWordsPagesWordListPageRoute
  '/onboarding/workspace': typeof DotModulesWorkspacePagesCreateWorkspacePageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_(authenticated)': typeof DotModulesShellPagesAuthenticatedLayoutRouteWithChildren
  '/_(onboarding)': typeof DotModulesWorkspacePagesOnboardingLayoutRouteWithChildren
  '/_(unauthenticated)': typeof DotModulesShellPagesUnauthenticatedLayoutRouteWithChildren
  '/_(authenticated)/': typeof DotModulesHomePagesHomePageRoute
  '/_(authenticated)/achievements': typeof DotModulesHomePagesAchievementsPageRoute
  '/_(authenticated)/add-word': typeof DotModulesHomePagesAddWordPageRoute
  '/_(authenticated)/learn': typeof DotModulesHomePagesLearnPageRoute
  '/_(authenticated)/progress': typeof DotModulesHomePagesProgressPageRoute
  '/_(authenticated)/review': typeof DotModulesHomePagesReviewPageRoute
  '/_(authenticated)/settings': typeof DotModulesHomePagesSettingsPageRoute
  '/_(authenticated)/topic': typeof DotModulesTopicPagesTopicPageRouteWithChildren
  '/_(unauthenticated)/login': typeof DotModulesAuthPagesLoginPageRoute
  '/_(unauthenticated)/register': typeof DotModulesAuthPagesRegisterPageRoute
  '/_(authenticated)/topic/$topicId': typeof DotModulesWordsPagesWordListPageRoute
  '/_(onboarding)/onboarding/workspace': typeof DotModulesWorkspacePagesCreateWorkspacePageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/add-word'
    | '/learn'
    | '/progress'
    | '/review'
    | '/settings'
    | '/topic'
    | '/login'
    | '/register'
    | '/topic/$topicId'
    | '/onboarding/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/add-word'
    | '/learn'
    | '/progress'
    | '/review'
    | '/settings'
    | '/topic'
    | '/login'
    | '/register'
    | '/topic/$topicId'
    | '/onboarding/workspace'
  id:
    | '__root__'
    | '/_(authenticated)'
    | '/_(onboarding)'
    | '/_(unauthenticated)'
    | '/_(authenticated)/'
    | '/_(authenticated)/achievements'
    | '/_(authenticated)/add-word'
    | '/_(authenticated)/learn'
    | '/_(authenticated)/progress'
    | '/_(authenticated)/review'
    | '/_(authenticated)/settings'
    | '/_(authenticated)/topic'
    | '/_(unauthenticated)/login'
    | '/_(unauthenticated)/register'
    | '/_(authenticated)/topic/$topicId'
    | '/_(onboarding)/onboarding/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DotModulesShellPagesAuthenticatedLayoutRoute: typeof DotModulesShellPagesAuthenticatedLayoutRouteWithChildren
  DotModulesWorkspacePagesOnboardingLayoutRoute: typeof DotModulesWorkspacePagesOnboardingLayoutRouteWithChildren
  DotModulesShellPagesUnauthenticatedLayoutRoute: typeof DotModulesShellPagesUnauthenticatedLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_(unauthenticated)': {
      id: '/_(unauthenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DotModulesShellPagesUnauthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_(onboarding)': {
      id: '/_(onboarding)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DotModulesWorkspacePagesOnboardingLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_(authenticated)': {
      id: '/_(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DotModulesShellPagesAuthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_(unauthenticated)/register': {
      id: '/_(unauthenticated)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof DotModulesAuthPagesRegisterPageRouteImport
      parentRoute: typeof DotModulesShellPagesUnauthenticatedLayoutRoute
    }
    '/_(unauthenticated)/login': {
      id: '/_(unauthenticated)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof DotModulesAuthPagesLoginPageRouteImport
      parentRoute: typeof DotModulesShellPagesUnauthenticatedLayoutRoute
    }
    '/_(authenticated)/topic': {
      id: '/_(authenticated)/topic'
      path: '/topic'
      fullPath: '/topic'
      preLoaderRoute: typeof DotModulesTopicPagesTopicPageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/settings': {
      id: '/_(authenticated)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DotModulesHomePagesSettingsPageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/review': {
      id: '/_(authenticated)/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof DotModulesHomePagesReviewPageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/progress': {
      id: '/_(authenticated)/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof DotModulesHomePagesProgressPageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/learn': {
      id: '/_(authenticated)/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof DotModulesHomePagesLearnPageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/add-word': {
      id: '/_(authenticated)/add-word'
      path: '/add-word'
      fullPath: '/add-word'
      preLoaderRoute: typeof DotModulesHomePagesAddWordPageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/achievements': {
      id: '/_(authenticated)/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof DotModulesHomePagesAchievementsPageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/': {
      id: '/_(authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DotModulesHomePagesHomePageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(onboarding)/onboarding/workspace': {
      id: '/_(onboarding)/onboarding/workspace'
      path: '/onboarding/workspace'
      fullPath: '/onboarding/workspace'
      preLoaderRoute: typeof DotModulesWorkspacePagesCreateWorkspacePageRouteImport
      parentRoute: typeof DotModulesWorkspacePagesOnboardingLayoutRoute
    }
    '/_(authenticated)/topic/$topicId': {
      id: '/_(authenticated)/topic/$topicId'
      path: '/$topicId'
      fullPath: '/topic/$topicId'
      preLoaderRoute: typeof DotModulesWordsPagesWordListPageRouteImport
      parentRoute: typeof DotModulesTopicPagesTopicPageRoute
    }
  }
}

interface DotModulesTopicPagesTopicPageRouteChildren {
  DotModulesWordsPagesWordListPageRoute: typeof DotModulesWordsPagesWordListPageRoute
}

const DotModulesTopicPagesTopicPageRouteChildren: DotModulesTopicPagesTopicPageRouteChildren =
  {
    DotModulesWordsPagesWordListPageRoute:
      DotModulesWordsPagesWordListPageRoute,
  }

const DotModulesTopicPagesTopicPageRouteWithChildren =
  DotModulesTopicPagesTopicPageRoute._addFileChildren(
    DotModulesTopicPagesTopicPageRouteChildren,
  )

interface DotModulesShellPagesAuthenticatedLayoutRouteChildren {
  DotModulesHomePagesHomePageRoute: typeof DotModulesHomePagesHomePageRoute
  DotModulesHomePagesAchievementsPageRoute: typeof DotModulesHomePagesAchievementsPageRoute
  DotModulesHomePagesAddWordPageRoute: typeof DotModulesHomePagesAddWordPageRoute
  DotModulesHomePagesLearnPageRoute: typeof DotModulesHomePagesLearnPageRoute
  DotModulesHomePagesProgressPageRoute: typeof DotModulesHomePagesProgressPageRoute
  DotModulesHomePagesReviewPageRoute: typeof DotModulesHomePagesReviewPageRoute
  DotModulesHomePagesSettingsPageRoute: typeof DotModulesHomePagesSettingsPageRoute
  DotModulesTopicPagesTopicPageRoute: typeof DotModulesTopicPagesTopicPageRouteWithChildren
}

const DotModulesShellPagesAuthenticatedLayoutRouteChildren: DotModulesShellPagesAuthenticatedLayoutRouteChildren =
  {
    DotModulesHomePagesHomePageRoute: DotModulesHomePagesHomePageRoute,
    DotModulesHomePagesAchievementsPageRoute:
      DotModulesHomePagesAchievementsPageRoute,
    DotModulesHomePagesAddWordPageRoute: DotModulesHomePagesAddWordPageRoute,
    DotModulesHomePagesLearnPageRoute: DotModulesHomePagesLearnPageRoute,
    DotModulesHomePagesProgressPageRoute: DotModulesHomePagesProgressPageRoute,
    DotModulesHomePagesReviewPageRoute: DotModulesHomePagesReviewPageRoute,
    DotModulesHomePagesSettingsPageRoute: DotModulesHomePagesSettingsPageRoute,
    DotModulesTopicPagesTopicPageRoute:
      DotModulesTopicPagesTopicPageRouteWithChildren,
  }

const DotModulesShellPagesAuthenticatedLayoutRouteWithChildren =
  DotModulesShellPagesAuthenticatedLayoutRoute._addFileChildren(
    DotModulesShellPagesAuthenticatedLayoutRouteChildren,
  )

interface DotModulesWorkspacePagesOnboardingLayoutRouteChildren {
  DotModulesWorkspacePagesCreateWorkspacePageRoute: typeof DotModulesWorkspacePagesCreateWorkspacePageRoute
}

const DotModulesWorkspacePagesOnboardingLayoutRouteChildren: DotModulesWorkspacePagesOnboardingLayoutRouteChildren =
  {
    DotModulesWorkspacePagesCreateWorkspacePageRoute:
      DotModulesWorkspacePagesCreateWorkspacePageRoute,
  }

const DotModulesWorkspacePagesOnboardingLayoutRouteWithChildren =
  DotModulesWorkspacePagesOnboardingLayoutRoute._addFileChildren(
    DotModulesWorkspacePagesOnboardingLayoutRouteChildren,
  )

interface DotModulesShellPagesUnauthenticatedLayoutRouteChildren {
  DotModulesAuthPagesLoginPageRoute: typeof DotModulesAuthPagesLoginPageRoute
  DotModulesAuthPagesRegisterPageRoute: typeof DotModulesAuthPagesRegisterPageRoute
}

const DotModulesShellPagesUnauthenticatedLayoutRouteChildren: DotModulesShellPagesUnauthenticatedLayoutRouteChildren =
  {
    DotModulesAuthPagesLoginPageRoute: DotModulesAuthPagesLoginPageRoute,
    DotModulesAuthPagesRegisterPageRoute: DotModulesAuthPagesRegisterPageRoute,
  }

const DotModulesShellPagesUnauthenticatedLayoutRouteWithChildren =
  DotModulesShellPagesUnauthenticatedLayoutRoute._addFileChildren(
    DotModulesShellPagesUnauthenticatedLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  DotModulesShellPagesAuthenticatedLayoutRoute:
    DotModulesShellPagesAuthenticatedLayoutRouteWithChildren,
  DotModulesWorkspacePagesOnboardingLayoutRoute:
    DotModulesWorkspacePagesOnboardingLayoutRouteWithChildren,
  DotModulesShellPagesUnauthenticatedLayoutRoute:
    DotModulesShellPagesUnauthenticatedLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
