/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './root'
import { Route as DotModulesShellPagesUnauthenticatedLayoutRouteImport } from './modules/shell/pages/unauthenticated-layout'
import { Route as DotModulesShellPagesAuthenticatedLayoutRouteImport } from './modules/shell/pages/authenticated-layout'
import { Route as DotModulesAuthPagesLoginPageRouteImport } from './modules/auth/pages/login-page'
import { Route as DotModulesTopicPagesTopicPageRouteImport } from './modules/topic/pages/topic-page'
import { Route as DotModulesHomePagesHomePageRouteImport } from './modules/home/pages/home-page'
import { Route as DotModulesWordsPagesWordListPageRouteImport } from './modules/words/pages/word-list-page'

const DotModulesShellPagesUnauthenticatedLayoutRoute =
  DotModulesShellPagesUnauthenticatedLayoutRouteImport.update({
    id: '/_(unauthenticated)',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotModulesShellPagesAuthenticatedLayoutRoute =
  DotModulesShellPagesAuthenticatedLayoutRouteImport.update({
    id: '/_(authenticated)',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotModulesAuthPagesLoginPageRoute =
  DotModulesAuthPagesLoginPageRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => DotModulesShellPagesUnauthenticatedLayoutRoute,
  } as any)
const DotModulesTopicPagesTopicPageRoute =
  DotModulesTopicPagesTopicPageRouteImport.update({
    id: '/topic',
    path: '/topic',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesHomePagesHomePageRoute =
  DotModulesHomePagesHomePageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesWordsPagesWordListPageRoute =
  DotModulesWordsPagesWordListPageRouteImport.update({
    id: '/$topicId',
    path: '/$topicId',
    getParentRoute: () => DotModulesTopicPagesTopicPageRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DotModulesHomePagesHomePageRoute
  '/topic': typeof DotModulesTopicPagesTopicPageRouteWithChildren
  '/login': typeof DotModulesAuthPagesLoginPageRoute
  '/topic/$topicId': typeof DotModulesWordsPagesWordListPageRoute
}
export interface FileRoutesByTo {
  '/': typeof DotModulesHomePagesHomePageRoute
  '/topic': typeof DotModulesTopicPagesTopicPageRouteWithChildren
  '/login': typeof DotModulesAuthPagesLoginPageRoute
  '/topic/$topicId': typeof DotModulesWordsPagesWordListPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_(authenticated)': typeof DotModulesShellPagesAuthenticatedLayoutRouteWithChildren
  '/_(unauthenticated)': typeof DotModulesShellPagesUnauthenticatedLayoutRouteWithChildren
  '/_(authenticated)/': typeof DotModulesHomePagesHomePageRoute
  '/_(authenticated)/topic': typeof DotModulesTopicPagesTopicPageRouteWithChildren
  '/_(unauthenticated)/login': typeof DotModulesAuthPagesLoginPageRoute
  '/_(authenticated)/topic/$topicId': typeof DotModulesWordsPagesWordListPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/topic' | '/login' | '/topic/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/topic' | '/login' | '/topic/$topicId'
  id:
    | '__root__'
    | '/_(authenticated)'
    | '/_(unauthenticated)'
    | '/_(authenticated)/'
    | '/_(authenticated)/topic'
    | '/_(unauthenticated)/login'
    | '/_(authenticated)/topic/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DotModulesShellPagesAuthenticatedLayoutRoute: typeof DotModulesShellPagesAuthenticatedLayoutRouteWithChildren
  DotModulesShellPagesUnauthenticatedLayoutRoute: typeof DotModulesShellPagesUnauthenticatedLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_(unauthenticated)': {
      id: '/_(unauthenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DotModulesShellPagesUnauthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_(authenticated)': {
      id: '/_(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DotModulesShellPagesAuthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_(unauthenticated)/login': {
      id: '/_(unauthenticated)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof DotModulesAuthPagesLoginPageRouteImport
      parentRoute: typeof DotModulesShellPagesUnauthenticatedLayoutRoute
    }
    '/_(authenticated)/topic': {
      id: '/_(authenticated)/topic'
      path: '/topic'
      fullPath: '/topic'
      preLoaderRoute: typeof DotModulesTopicPagesTopicPageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/': {
      id: '/_(authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DotModulesHomePagesHomePageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/topic/$topicId': {
      id: '/_(authenticated)/topic/$topicId'
      path: '/$topicId'
      fullPath: '/topic/$topicId'
      preLoaderRoute: typeof DotModulesWordsPagesWordListPageRouteImport
      parentRoute: typeof DotModulesTopicPagesTopicPageRoute
    }
  }
}

interface DotModulesTopicPagesTopicPageRouteChildren {
  DotModulesWordsPagesWordListPageRoute: typeof DotModulesWordsPagesWordListPageRoute
}

const DotModulesTopicPagesTopicPageRouteChildren: DotModulesTopicPagesTopicPageRouteChildren =
  {
    DotModulesWordsPagesWordListPageRoute:
      DotModulesWordsPagesWordListPageRoute,
  }

const DotModulesTopicPagesTopicPageRouteWithChildren =
  DotModulesTopicPagesTopicPageRoute._addFileChildren(
    DotModulesTopicPagesTopicPageRouteChildren,
  )

interface DotModulesShellPagesAuthenticatedLayoutRouteChildren {
  DotModulesHomePagesHomePageRoute: typeof DotModulesHomePagesHomePageRoute
  DotModulesTopicPagesTopicPageRoute: typeof DotModulesTopicPagesTopicPageRouteWithChildren
}

const DotModulesShellPagesAuthenticatedLayoutRouteChildren: DotModulesShellPagesAuthenticatedLayoutRouteChildren =
  {
    DotModulesHomePagesHomePageRoute: DotModulesHomePagesHomePageRoute,
    DotModulesTopicPagesTopicPageRoute:
      DotModulesTopicPagesTopicPageRouteWithChildren,
  }

const DotModulesShellPagesAuthenticatedLayoutRouteWithChildren =
  DotModulesShellPagesAuthenticatedLayoutRoute._addFileChildren(
    DotModulesShellPagesAuthenticatedLayoutRouteChildren,
  )

interface DotModulesShellPagesUnauthenticatedLayoutRouteChildren {
  DotModulesAuthPagesLoginPageRoute: typeof DotModulesAuthPagesLoginPageRoute
}

const DotModulesShellPagesUnauthenticatedLayoutRouteChildren: DotModulesShellPagesUnauthenticatedLayoutRouteChildren =
  {
    DotModulesAuthPagesLoginPageRoute: DotModulesAuthPagesLoginPageRoute,
  }

const DotModulesShellPagesUnauthenticatedLayoutRouteWithChildren =
  DotModulesShellPagesUnauthenticatedLayoutRoute._addFileChildren(
    DotModulesShellPagesUnauthenticatedLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  DotModulesShellPagesAuthenticatedLayoutRoute:
    DotModulesShellPagesAuthenticatedLayoutRouteWithChildren,
  DotModulesShellPagesUnauthenticatedLayoutRoute:
    DotModulesShellPagesUnauthenticatedLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
