/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './root'
import { Route as DotModulesShellPagesUnauthenticatedLayoutRouteImport } from './modules/shell/pages/unauthenticated-layout'
import { Route as DotModulesWorkspacePagesOnboardingLayoutRouteImport } from './modules/workspace/pages/onboarding-layout'
import { Route as DotModulesShellPagesAuthenticatedLayoutRouteImport } from './modules/shell/pages/authenticated-layout'
import { Route as DotModulesAuthPagesRegisterPageRouteImport } from './modules/auth/pages/register-page'
import { Route as DotModulesAuthPagesLoginPageRouteImport } from './modules/auth/pages/login-page'
import { Route as DotModulesHomePagesSettingsPageRouteImport } from './modules/home/pages/settings-page'
import { Route as DotModulesHomePagesReviewPageRouteImport } from './modules/home/pages/review-page'
import { Route as DotModulesHomePagesProgressPageRouteImport } from './modules/home/pages/progress-page'
import { Route as DotModulesHomePagesLearnPageRouteImport } from './modules/home/pages/learn-page'
import { Route as DotModulesHomePagesAddWordPageRouteImport } from './modules/home/pages/add-word-page'
import { Route as DotModulesHomePagesAchievementsPageRouteImport } from './modules/home/pages/achievements-page'
import { Route as DotModulesHomePagesHomePageRouteImport } from './modules/home/pages/home-page'
import { Route as DotModulesWorkspacePagesCreateWorkspacePageRouteImport } from './modules/workspace/pages/create-workspace-page'
import { Route as DotModulesWordDetailPagesKeywordRouteImport } from './modules/word-detail/pages/$keyword'
import { Route as DotModulesTopicPagesTopicLayoutRouteImport } from './modules/topic/pages/topic-layout'
import { Route as DotModulesTopicPagesTopicDetailPageRouteImport } from './modules/topic/pages/topic-detail-page'
import { Route as DotModulesTopicPagesTopicPageRouteImport } from './modules/topic/pages/topic-page'

const authenticatedRouteImport = createFileRoute('/_(authenticated)/_')()

const DotModulesShellPagesUnauthenticatedLayoutRoute =
  DotModulesShellPagesUnauthenticatedLayoutRouteImport.update({
    id: '/_(unauthenticated)',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotModulesWorkspacePagesOnboardingLayoutRoute =
  DotModulesWorkspacePagesOnboardingLayoutRouteImport.update({
    id: '/_(onboarding)',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotModulesShellPagesAuthenticatedLayoutRoute =
  DotModulesShellPagesAuthenticatedLayoutRouteImport.update({
    id: '/_(authenticated)',
    getParentRoute: () => rootRouteImport,
  } as any)
const authenticatedRoute = authenticatedRouteImport.update({
  id: '/_',
  getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
} as any)
const DotModulesAuthPagesRegisterPageRoute =
  DotModulesAuthPagesRegisterPageRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => DotModulesShellPagesUnauthenticatedLayoutRoute,
  } as any)
const DotModulesAuthPagesLoginPageRoute =
  DotModulesAuthPagesLoginPageRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => DotModulesShellPagesUnauthenticatedLayoutRoute,
  } as any)
const DotModulesHomePagesSettingsPageRoute =
  DotModulesHomePagesSettingsPageRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesHomePagesReviewPageRoute =
  DotModulesHomePagesReviewPageRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesHomePagesProgressPageRoute =
  DotModulesHomePagesProgressPageRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesHomePagesLearnPageRoute =
  DotModulesHomePagesLearnPageRouteImport.update({
    id: '/learn',
    path: '/learn',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesHomePagesAddWordPageRoute =
  DotModulesHomePagesAddWordPageRouteImport.update({
    id: '/add-word',
    path: '/add-word',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesHomePagesAchievementsPageRoute =
  DotModulesHomePagesAchievementsPageRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesHomePagesHomePageRoute =
  DotModulesHomePagesHomePageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesWorkspacePagesCreateWorkspacePageRoute =
  DotModulesWorkspacePagesCreateWorkspacePageRouteImport.update({
    id: '/onboarding/workspace',
    path: '/onboarding/workspace',
    getParentRoute: () => DotModulesWorkspacePagesOnboardingLayoutRoute,
  } as any)
const DotModulesWordDetailPagesKeywordRoute =
  DotModulesWordDetailPagesKeywordRouteImport.update({
    id: '/dictionary/$keyword',
    path: '/dictionary/$keyword',
    getParentRoute: () => DotModulesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotModulesTopicPagesTopicLayoutRoute =
  DotModulesTopicPagesTopicLayoutRouteImport.update({
    id: '/topic',
    path: '/topic',
    getParentRoute: () => authenticatedRoute,
  } as any)
const DotModulesTopicPagesTopicDetailPageRoute =
  DotModulesTopicPagesTopicDetailPageRouteImport.update({
    id: '/$topicId',
    path: '/$topicId',
    getParentRoute: () => DotModulesTopicPagesTopicLayoutRoute,
  } as any)
const DotModulesTopicPagesTopicPageRoute =
  DotModulesTopicPagesTopicPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DotModulesTopicPagesTopicLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DotModulesHomePagesHomePageRoute
  '/achievements': typeof DotModulesHomePagesAchievementsPageRoute
  '/add-word': typeof DotModulesHomePagesAddWordPageRoute
  '/learn': typeof DotModulesHomePagesLearnPageRoute
  '/progress': typeof DotModulesHomePagesProgressPageRoute
  '/review': typeof DotModulesHomePagesReviewPageRoute
  '/settings': typeof DotModulesHomePagesSettingsPageRoute
  '/login': typeof DotModulesAuthPagesLoginPageRoute
  '/register': typeof DotModulesAuthPagesRegisterPageRoute
  '/topic': typeof DotModulesTopicPagesTopicLayoutRouteWithChildren
  '/dictionary/$keyword': typeof DotModulesWordDetailPagesKeywordRoute
  '/onboarding/workspace': typeof DotModulesWorkspacePagesCreateWorkspacePageRoute
  '/topic/': typeof DotModulesTopicPagesTopicPageRoute
  '/topic/$topicId': typeof DotModulesTopicPagesTopicDetailPageRoute
}
export interface FileRoutesByTo {
  '/': typeof DotModulesHomePagesHomePageRoute
  '/achievements': typeof DotModulesHomePagesAchievementsPageRoute
  '/add-word': typeof DotModulesHomePagesAddWordPageRoute
  '/learn': typeof DotModulesHomePagesLearnPageRoute
  '/progress': typeof DotModulesHomePagesProgressPageRoute
  '/review': typeof DotModulesHomePagesReviewPageRoute
  '/settings': typeof DotModulesHomePagesSettingsPageRoute
  '/login': typeof DotModulesAuthPagesLoginPageRoute
  '/register': typeof DotModulesAuthPagesRegisterPageRoute
  '/dictionary/$keyword': typeof DotModulesWordDetailPagesKeywordRoute
  '/onboarding/workspace': typeof DotModulesWorkspacePagesCreateWorkspacePageRoute
  '/topic': typeof DotModulesTopicPagesTopicPageRoute
  '/topic/$topicId': typeof DotModulesTopicPagesTopicDetailPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_(authenticated)': typeof DotModulesShellPagesAuthenticatedLayoutRouteWithChildren
  '/_(onboarding)': typeof DotModulesWorkspacePagesOnboardingLayoutRouteWithChildren
  '/_(unauthenticated)': typeof DotModulesShellPagesUnauthenticatedLayoutRouteWithChildren
  '/_(authenticated)/': typeof DotModulesHomePagesHomePageRoute
  '/_(authenticated)/achievements': typeof DotModulesHomePagesAchievementsPageRoute
  '/_(authenticated)/add-word': typeof DotModulesHomePagesAddWordPageRoute
  '/_(authenticated)/learn': typeof DotModulesHomePagesLearnPageRoute
  '/_(authenticated)/progress': typeof DotModulesHomePagesProgressPageRoute
  '/_(authenticated)/review': typeof DotModulesHomePagesReviewPageRoute
  '/_(authenticated)/settings': typeof DotModulesHomePagesSettingsPageRoute
  '/_(unauthenticated)/login': typeof DotModulesAuthPagesLoginPageRoute
  '/_(unauthenticated)/register': typeof DotModulesAuthPagesRegisterPageRoute
  '/_(authenticated)/_': typeof authenticatedRouteWithChildren
  '/_(authenticated)/_/topic': typeof DotModulesTopicPagesTopicLayoutRouteWithChildren
  '/_(authenticated)/dictionary/$keyword': typeof DotModulesWordDetailPagesKeywordRoute
  '/_(onboarding)/onboarding/workspace': typeof DotModulesWorkspacePagesCreateWorkspacePageRoute
  '/_(authenticated)/_/topic/': typeof DotModulesTopicPagesTopicPageRoute
  '/_(authenticated)/_/topic/$topicId': typeof DotModulesTopicPagesTopicDetailPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/add-word'
    | '/learn'
    | '/progress'
    | '/review'
    | '/settings'
    | '/login'
    | '/register'
    | '/topic'
    | '/dictionary/$keyword'
    | '/onboarding/workspace'
    | '/topic/'
    | '/topic/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/add-word'
    | '/learn'
    | '/progress'
    | '/review'
    | '/settings'
    | '/login'
    | '/register'
    | '/dictionary/$keyword'
    | '/onboarding/workspace'
    | '/topic'
    | '/topic/$topicId'
  id:
    | '__root__'
    | '/_(authenticated)'
    | '/_(onboarding)'
    | '/_(unauthenticated)'
    | '/_(authenticated)/'
    | '/_(authenticated)/achievements'
    | '/_(authenticated)/add-word'
    | '/_(authenticated)/learn'
    | '/_(authenticated)/progress'
    | '/_(authenticated)/review'
    | '/_(authenticated)/settings'
    | '/_(unauthenticated)/login'
    | '/_(unauthenticated)/register'
    | '/_(authenticated)/_'
    | '/_(authenticated)/_/topic'
    | '/_(authenticated)/dictionary/$keyword'
    | '/_(onboarding)/onboarding/workspace'
    | '/_(authenticated)/_/topic/'
    | '/_(authenticated)/_/topic/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DotModulesShellPagesAuthenticatedLayoutRoute: typeof DotModulesShellPagesAuthenticatedLayoutRouteWithChildren
  DotModulesWorkspacePagesOnboardingLayoutRoute: typeof DotModulesWorkspacePagesOnboardingLayoutRouteWithChildren
  DotModulesShellPagesUnauthenticatedLayoutRoute: typeof DotModulesShellPagesUnauthenticatedLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_(unauthenticated)': {
      id: '/_(unauthenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DotModulesShellPagesUnauthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_(onboarding)': {
      id: '/_(onboarding)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DotModulesWorkspacePagesOnboardingLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_(authenticated)': {
      id: '/_(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DotModulesShellPagesAuthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_(authenticated)/_': {
      id: '/_(authenticated)/_'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(unauthenticated)/register': {
      id: '/_(unauthenticated)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof DotModulesAuthPagesRegisterPageRouteImport
      parentRoute: typeof DotModulesShellPagesUnauthenticatedLayoutRoute
    }
    '/_(unauthenticated)/login': {
      id: '/_(unauthenticated)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof DotModulesAuthPagesLoginPageRouteImport
      parentRoute: typeof DotModulesShellPagesUnauthenticatedLayoutRoute
    }
    '/_(authenticated)/settings': {
      id: '/_(authenticated)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DotModulesHomePagesSettingsPageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/review': {
      id: '/_(authenticated)/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof DotModulesHomePagesReviewPageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/progress': {
      id: '/_(authenticated)/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof DotModulesHomePagesProgressPageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/learn': {
      id: '/_(authenticated)/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof DotModulesHomePagesLearnPageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/add-word': {
      id: '/_(authenticated)/add-word'
      path: '/add-word'
      fullPath: '/add-word'
      preLoaderRoute: typeof DotModulesHomePagesAddWordPageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/achievements': {
      id: '/_(authenticated)/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof DotModulesHomePagesAchievementsPageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/': {
      id: '/_(authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DotModulesHomePagesHomePageRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(onboarding)/onboarding/workspace': {
      id: '/_(onboarding)/onboarding/workspace'
      path: '/onboarding/workspace'
      fullPath: '/onboarding/workspace'
      preLoaderRoute: typeof DotModulesWorkspacePagesCreateWorkspacePageRouteImport
      parentRoute: typeof DotModulesWorkspacePagesOnboardingLayoutRoute
    }
    '/_(authenticated)/dictionary/$keyword': {
      id: '/_(authenticated)/dictionary/$keyword'
      path: '/dictionary/$keyword'
      fullPath: '/dictionary/$keyword'
      preLoaderRoute: typeof DotModulesWordDetailPagesKeywordRouteImport
      parentRoute: typeof DotModulesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/_/topic': {
      id: '/_(authenticated)/_/topic'
      path: '/topic'
      fullPath: '/topic'
      preLoaderRoute: typeof DotModulesTopicPagesTopicLayoutRouteImport
      parentRoute: typeof authenticatedRoute
    }
    '/_(authenticated)/_/topic/$topicId': {
      id: '/_(authenticated)/_/topic/$topicId'
      path: '/$topicId'
      fullPath: '/topic/$topicId'
      preLoaderRoute: typeof DotModulesTopicPagesTopicDetailPageRouteImport
      parentRoute: typeof DotModulesTopicPagesTopicLayoutRoute
    }
    '/_(authenticated)/_/topic/': {
      id: '/_(authenticated)/_/topic/'
      path: '/'
      fullPath: '/topic/'
      preLoaderRoute: typeof DotModulesTopicPagesTopicPageRouteImport
      parentRoute: typeof DotModulesTopicPagesTopicLayoutRoute
    }
  }
}

interface DotModulesTopicPagesTopicLayoutRouteChildren {
  DotModulesTopicPagesTopicPageRoute: typeof DotModulesTopicPagesTopicPageRoute
  DotModulesTopicPagesTopicDetailPageRoute: typeof DotModulesTopicPagesTopicDetailPageRoute
}

const DotModulesTopicPagesTopicLayoutRouteChildren: DotModulesTopicPagesTopicLayoutRouteChildren =
  {
    DotModulesTopicPagesTopicPageRoute: DotModulesTopicPagesTopicPageRoute,
    DotModulesTopicPagesTopicDetailPageRoute:
      DotModulesTopicPagesTopicDetailPageRoute,
  }

const DotModulesTopicPagesTopicLayoutRouteWithChildren =
  DotModulesTopicPagesTopicLayoutRoute._addFileChildren(
    DotModulesTopicPagesTopicLayoutRouteChildren,
  )

interface authenticatedRouteChildren {
  DotModulesTopicPagesTopicLayoutRoute: typeof DotModulesTopicPagesTopicLayoutRouteWithChildren
}

const authenticatedRouteChildren: authenticatedRouteChildren = {
  DotModulesTopicPagesTopicLayoutRoute:
    DotModulesTopicPagesTopicLayoutRouteWithChildren,
}

const authenticatedRouteWithChildren = authenticatedRoute._addFileChildren(
  authenticatedRouteChildren,
)

interface DotModulesShellPagesAuthenticatedLayoutRouteChildren {
  DotModulesHomePagesHomePageRoute: typeof DotModulesHomePagesHomePageRoute
  DotModulesHomePagesAchievementsPageRoute: typeof DotModulesHomePagesAchievementsPageRoute
  DotModulesHomePagesAddWordPageRoute: typeof DotModulesHomePagesAddWordPageRoute
  DotModulesHomePagesLearnPageRoute: typeof DotModulesHomePagesLearnPageRoute
  DotModulesHomePagesProgressPageRoute: typeof DotModulesHomePagesProgressPageRoute
  DotModulesHomePagesReviewPageRoute: typeof DotModulesHomePagesReviewPageRoute
  DotModulesHomePagesSettingsPageRoute: typeof DotModulesHomePagesSettingsPageRoute
  authenticatedRoute: typeof authenticatedRouteWithChildren
  DotModulesWordDetailPagesKeywordRoute: typeof DotModulesWordDetailPagesKeywordRoute
}

const DotModulesShellPagesAuthenticatedLayoutRouteChildren: DotModulesShellPagesAuthenticatedLayoutRouteChildren =
  {
    DotModulesHomePagesHomePageRoute: DotModulesHomePagesHomePageRoute,
    DotModulesHomePagesAchievementsPageRoute:
      DotModulesHomePagesAchievementsPageRoute,
    DotModulesHomePagesAddWordPageRoute: DotModulesHomePagesAddWordPageRoute,
    DotModulesHomePagesLearnPageRoute: DotModulesHomePagesLearnPageRoute,
    DotModulesHomePagesProgressPageRoute: DotModulesHomePagesProgressPageRoute,
    DotModulesHomePagesReviewPageRoute: DotModulesHomePagesReviewPageRoute,
    DotModulesHomePagesSettingsPageRoute: DotModulesHomePagesSettingsPageRoute,
    authenticatedRoute: authenticatedRouteWithChildren,
    DotModulesWordDetailPagesKeywordRoute:
      DotModulesWordDetailPagesKeywordRoute,
  }

const DotModulesShellPagesAuthenticatedLayoutRouteWithChildren =
  DotModulesShellPagesAuthenticatedLayoutRoute._addFileChildren(
    DotModulesShellPagesAuthenticatedLayoutRouteChildren,
  )

interface DotModulesWorkspacePagesOnboardingLayoutRouteChildren {
  DotModulesWorkspacePagesCreateWorkspacePageRoute: typeof DotModulesWorkspacePagesCreateWorkspacePageRoute
}

const DotModulesWorkspacePagesOnboardingLayoutRouteChildren: DotModulesWorkspacePagesOnboardingLayoutRouteChildren =
  {
    DotModulesWorkspacePagesCreateWorkspacePageRoute:
      DotModulesWorkspacePagesCreateWorkspacePageRoute,
  }

const DotModulesWorkspacePagesOnboardingLayoutRouteWithChildren =
  DotModulesWorkspacePagesOnboardingLayoutRoute._addFileChildren(
    DotModulesWorkspacePagesOnboardingLayoutRouteChildren,
  )

interface DotModulesShellPagesUnauthenticatedLayoutRouteChildren {
  DotModulesAuthPagesLoginPageRoute: typeof DotModulesAuthPagesLoginPageRoute
  DotModulesAuthPagesRegisterPageRoute: typeof DotModulesAuthPagesRegisterPageRoute
}

const DotModulesShellPagesUnauthenticatedLayoutRouteChildren: DotModulesShellPagesUnauthenticatedLayoutRouteChildren =
  {
    DotModulesAuthPagesLoginPageRoute: DotModulesAuthPagesLoginPageRoute,
    DotModulesAuthPagesRegisterPageRoute: DotModulesAuthPagesRegisterPageRoute,
  }

const DotModulesShellPagesUnauthenticatedLayoutRouteWithChildren =
  DotModulesShellPagesUnauthenticatedLayoutRoute._addFileChildren(
    DotModulesShellPagesUnauthenticatedLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  DotModulesShellPagesAuthenticatedLayoutRoute:
    DotModulesShellPagesAuthenticatedLayoutRouteWithChildren,
  DotModulesWorkspacePagesOnboardingLayoutRoute:
    DotModulesWorkspacePagesOnboardingLayoutRouteWithChildren,
  DotModulesShellPagesUnauthenticatedLayoutRoute:
    DotModulesShellPagesUnauthenticatedLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
