/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './root'
import { Route as DotFeaturesShellPagesUnauthenticatedLayoutRouteImport } from './features/shell/pages/unauthenticated-layout'
import { Route as DotFeaturesShellPagesAuthenticatedLayoutRouteImport } from './features/shell/pages/authenticated-layout'
import { Route as DotFeaturesSettingsPagesIndexRouteImport } from './features/settings/pages/index'
import { Route as DotFeaturesAuthPagesLoginPageRouteImport } from './features/auth/pages/login-page'
import { Route as DotFeaturesProductPagesProductPageRouteImport } from './features/product/pages/product-page'
import { Route as DotFeaturesHomePagesHomeRouteImport } from './features/home/pages/home'
import { Route as DotFeaturesProductPagesUpdateProductPageRouteImport } from './features/product/pages/update-product-page'
import { Route as DotFeaturesAccountPagesAccountProfilePageRouteImport } from './features/account/pages/account-profile-page'

const DotFeaturesShellPagesUnauthenticatedLayoutRoute =
  DotFeaturesShellPagesUnauthenticatedLayoutRouteImport.update({
    id: '/_(unauthenticated)',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotFeaturesShellPagesAuthenticatedLayoutRoute =
  DotFeaturesShellPagesAuthenticatedLayoutRouteImport.update({
    id: '/_(authenticated)',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotFeaturesSettingsPagesIndexRoute =
  DotFeaturesSettingsPagesIndexRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DotFeaturesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotFeaturesAuthPagesLoginPageRoute =
  DotFeaturesAuthPagesLoginPageRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => DotFeaturesShellPagesUnauthenticatedLayoutRoute,
  } as any)
const DotFeaturesProductPagesProductPageRoute =
  DotFeaturesProductPagesProductPageRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => DotFeaturesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotFeaturesHomePagesHomeRoute =
  DotFeaturesHomePagesHomeRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DotFeaturesShellPagesAuthenticatedLayoutRoute,
  } as any)
const DotFeaturesProductPagesUpdateProductPageRoute =
  DotFeaturesProductPagesUpdateProductPageRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => DotFeaturesProductPagesProductPageRoute,
  } as any)
const DotFeaturesAccountPagesAccountProfilePageRoute =
  DotFeaturesAccountPagesAccountProfilePageRouteImport.update({
    id: '/account/profile',
    path: '/account/profile',
    getParentRoute: () => DotFeaturesSettingsPagesIndexRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DotFeaturesHomePagesHomeRoute
  '/products': typeof DotFeaturesProductPagesProductPageRouteWithChildren
  '/login': typeof DotFeaturesAuthPagesLoginPageRoute
  '/settings': typeof DotFeaturesSettingsPagesIndexRouteWithChildren
  '/products/$productId': typeof DotFeaturesProductPagesUpdateProductPageRoute
  '/settings/account/profile': typeof DotFeaturesAccountPagesAccountProfilePageRoute
}
export interface FileRoutesByTo {
  '/': typeof DotFeaturesHomePagesHomeRoute
  '/products': typeof DotFeaturesProductPagesProductPageRouteWithChildren
  '/login': typeof DotFeaturesAuthPagesLoginPageRoute
  '/settings': typeof DotFeaturesSettingsPagesIndexRouteWithChildren
  '/products/$productId': typeof DotFeaturesProductPagesUpdateProductPageRoute
  '/settings/account/profile': typeof DotFeaturesAccountPagesAccountProfilePageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_(authenticated)': typeof DotFeaturesShellPagesAuthenticatedLayoutRouteWithChildren
  '/_(unauthenticated)': typeof DotFeaturesShellPagesUnauthenticatedLayoutRouteWithChildren
  '/_(authenticated)/': typeof DotFeaturesHomePagesHomeRoute
  '/_(authenticated)/products': typeof DotFeaturesProductPagesProductPageRouteWithChildren
  '/_(unauthenticated)/login': typeof DotFeaturesAuthPagesLoginPageRoute
  '/_(authenticated)/settings': typeof DotFeaturesSettingsPagesIndexRouteWithChildren
  '/_(authenticated)/products/$productId': typeof DotFeaturesProductPagesUpdateProductPageRoute
  '/_(authenticated)/settings/account/profile': typeof DotFeaturesAccountPagesAccountProfilePageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/products'
    | '/login'
    | '/settings'
    | '/products/$productId'
    | '/settings/account/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/products'
    | '/login'
    | '/settings'
    | '/products/$productId'
    | '/settings/account/profile'
  id:
    | '__root__'
    | '/_(authenticated)'
    | '/_(unauthenticated)'
    | '/_(authenticated)/'
    | '/_(authenticated)/products'
    | '/_(unauthenticated)/login'
    | '/_(authenticated)/settings'
    | '/_(authenticated)/products/$productId'
    | '/_(authenticated)/settings/account/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DotFeaturesShellPagesAuthenticatedLayoutRoute: typeof DotFeaturesShellPagesAuthenticatedLayoutRouteWithChildren
  DotFeaturesShellPagesUnauthenticatedLayoutRoute: typeof DotFeaturesShellPagesUnauthenticatedLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_(unauthenticated)': {
      id: '/_(unauthenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DotFeaturesShellPagesUnauthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_(authenticated)': {
      id: '/_(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DotFeaturesShellPagesAuthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_(authenticated)/settings': {
      id: '/_(authenticated)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DotFeaturesSettingsPagesIndexRouteImport
      parentRoute: typeof DotFeaturesShellPagesAuthenticatedLayoutRoute
    }
    '/_(unauthenticated)/login': {
      id: '/_(unauthenticated)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof DotFeaturesAuthPagesLoginPageRouteImport
      parentRoute: typeof DotFeaturesShellPagesUnauthenticatedLayoutRoute
    }
    '/_(authenticated)/products': {
      id: '/_(authenticated)/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof DotFeaturesProductPagesProductPageRouteImport
      parentRoute: typeof DotFeaturesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/': {
      id: '/_(authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DotFeaturesHomePagesHomeRouteImport
      parentRoute: typeof DotFeaturesShellPagesAuthenticatedLayoutRoute
    }
    '/_(authenticated)/products/$productId': {
      id: '/_(authenticated)/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof DotFeaturesProductPagesUpdateProductPageRouteImport
      parentRoute: typeof DotFeaturesProductPagesProductPageRoute
    }
    '/_(authenticated)/settings/account/profile': {
      id: '/_(authenticated)/settings/account/profile'
      path: '/account/profile'
      fullPath: '/settings/account/profile'
      preLoaderRoute: typeof DotFeaturesAccountPagesAccountProfilePageRouteImport
      parentRoute: typeof DotFeaturesSettingsPagesIndexRoute
    }
  }
}

interface DotFeaturesProductPagesProductPageRouteChildren {
  DotFeaturesProductPagesUpdateProductPageRoute: typeof DotFeaturesProductPagesUpdateProductPageRoute
}

const DotFeaturesProductPagesProductPageRouteChildren: DotFeaturesProductPagesProductPageRouteChildren =
  {
    DotFeaturesProductPagesUpdateProductPageRoute:
      DotFeaturesProductPagesUpdateProductPageRoute,
  }

const DotFeaturesProductPagesProductPageRouteWithChildren =
  DotFeaturesProductPagesProductPageRoute._addFileChildren(
    DotFeaturesProductPagesProductPageRouteChildren,
  )

interface DotFeaturesSettingsPagesIndexRouteChildren {
  DotFeaturesAccountPagesAccountProfilePageRoute: typeof DotFeaturesAccountPagesAccountProfilePageRoute
}

const DotFeaturesSettingsPagesIndexRouteChildren: DotFeaturesSettingsPagesIndexRouteChildren =
  {
    DotFeaturesAccountPagesAccountProfilePageRoute:
      DotFeaturesAccountPagesAccountProfilePageRoute,
  }

const DotFeaturesSettingsPagesIndexRouteWithChildren =
  DotFeaturesSettingsPagesIndexRoute._addFileChildren(
    DotFeaturesSettingsPagesIndexRouteChildren,
  )

interface DotFeaturesShellPagesAuthenticatedLayoutRouteChildren {
  DotFeaturesHomePagesHomeRoute: typeof DotFeaturesHomePagesHomeRoute
  DotFeaturesProductPagesProductPageRoute: typeof DotFeaturesProductPagesProductPageRouteWithChildren
  DotFeaturesSettingsPagesIndexRoute: typeof DotFeaturesSettingsPagesIndexRouteWithChildren
}

const DotFeaturesShellPagesAuthenticatedLayoutRouteChildren: DotFeaturesShellPagesAuthenticatedLayoutRouteChildren =
  {
    DotFeaturesHomePagesHomeRoute: DotFeaturesHomePagesHomeRoute,
    DotFeaturesProductPagesProductPageRoute:
      DotFeaturesProductPagesProductPageRouteWithChildren,
    DotFeaturesSettingsPagesIndexRoute:
      DotFeaturesSettingsPagesIndexRouteWithChildren,
  }

const DotFeaturesShellPagesAuthenticatedLayoutRouteWithChildren =
  DotFeaturesShellPagesAuthenticatedLayoutRoute._addFileChildren(
    DotFeaturesShellPagesAuthenticatedLayoutRouteChildren,
  )

interface DotFeaturesShellPagesUnauthenticatedLayoutRouteChildren {
  DotFeaturesAuthPagesLoginPageRoute: typeof DotFeaturesAuthPagesLoginPageRoute
}

const DotFeaturesShellPagesUnauthenticatedLayoutRouteChildren: DotFeaturesShellPagesUnauthenticatedLayoutRouteChildren =
  {
    DotFeaturesAuthPagesLoginPageRoute: DotFeaturesAuthPagesLoginPageRoute,
  }

const DotFeaturesShellPagesUnauthenticatedLayoutRouteWithChildren =
  DotFeaturesShellPagesUnauthenticatedLayoutRoute._addFileChildren(
    DotFeaturesShellPagesUnauthenticatedLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  DotFeaturesShellPagesAuthenticatedLayoutRoute:
    DotFeaturesShellPagesAuthenticatedLayoutRouteWithChildren,
  DotFeaturesShellPagesUnauthenticatedLayoutRoute:
    DotFeaturesShellPagesUnauthenticatedLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
